## Measures of Central Tendency

Here is a simple video to explain you the concepts:
https://www.youtube.com/watch?v=GrynkZB3E7M

### Mean

In [11]:
import statistics as stats # `as` is a keyword that is used create an alias `stats` for the statistics library 

In [12]:
# Given the following data (we will use a list here) :
student_grades = [79, 87, 99, 96, 88, 79, 75, 68, 90, 91, 67]  # Here are the grades of 11 students in a class 

In [13]:
stats.mean(student_grades)

83.54545454545455

### Median 

In [14]:
student_grades = [79, 87, 99, 96, 88, 79, 75, 68, 90, 91, 67]  # Here are the grades of 11 students in a class 

In [15]:
import numpy as np
np.sort(student_grades)  # This is a function we can use to sort the data in ascending order

array([67, 68, 75, 79, 79, 87, 88, 90, 91, 96, 99])

In [16]:
len(student_grades) # Number of data points in the list. 

11

In [17]:
# It should be the sixth term in the list. Note that `N` in the formula above for finding the mean 
# is a mathematical notation which does not follow zero based indexing as python

In [18]:
stats.median(student_grades)

87

In [19]:
# If the data had an even number of elements as shown below:

student_grades = [79, 87, 99, 96, 88, 79, 75, 68, 90, 91] 

In [20]:
np.sort(student_grades)

array([68, 75, 79, 79, 87, 88, 90, 91, 96, 99])

In [21]:
len(student_grades)

10

In [22]:
stats.median(student_grades)

87.5

### Mode

In [23]:
student_grades = [79, 87, 99, 96, 88, 79, 75, 68, 90, 91] 

In [24]:
stats.mode(student_grades)

79

In [25]:
student_grades = [87, 87, 99, 99, 96, 88, 79, 75, 68, 90, 91] 

In [26]:
stats.mode(student_grades)

87

In [27]:
# Now we will try to combine some things we learn in unit 1 to solve this problem

In [28]:
# Actual code is below:

In [29]:
counts_dict = {} # Defining an empty dictionary to store the count of each 
for item in student_grades:
    count_of_item = student_grades.count(item) # Count function to check the frequency of that item in the list 
    counts_dict[item] = count_of_item  # Creating a new key-value pair in each iteration

print(counts_dict)

{87: 2, 99: 2, 96: 1, 88: 1, 79: 1, 75: 1, 68: 1, 90: 1, 91: 1}


In [30]:
# The values in the dictionary are:
values = counts_dict.values()
print("Values of counts in the dictionary are: ", values)

max_value = max(values)  # To find the max of the frequency counts 
print("Max value in the counts is:", max_value)

Values of counts in the dictionary are:  dict_values([2, 2, 1, 1, 1, 1, 1, 1, 1])
Max value in the counts is: 2


In [31]:
# In a previous lesson on iterations, we saw how we can iterate on key value pair. This is the example that we
# looked at:
x = {'key1': 100 , 'key2': 200 , 'key3':300}
for key, value in x.items():
    print("For key: ", key, "- the value is: ", value)

For key:  key1 - the value is:  100
For key:  key2 - the value is:  200
For key:  key3 - the value is:  300


In [32]:
# we will use similar code to find the corresponding key for the value, if it equals the variable `max_value`

In [33]:
for key, value in counts_dict.items():
    if value == max_value:
        print("Mode: ", key)

Mode:  87
Mode:  99


### Exercise  

In [34]:
#Dataset cannot have more than one median

In [35]:
data = [4,  7,  5,  9,  8,  6,  7,  7,  8,  5,  6,  9,  8, 5,  8,  7,  4,  7, 3,  6,  8,  9,  7,  6,  9]

In [36]:
stats.mean(data)

6.72

In [37]:
stats.median(data)

7

In [38]:
stats.mode(data)

7

In [39]:
min(data)

3

In [40]:
max(data)

9

In [41]:
range of this data set is 6

SyntaxError: invalid syntax (3257481125.py, line 1)

In [43]:
data_dictionary = {}
data_dictionary["mean"] = stats.mean(data)
data_dictionary["median"] = stats.median(data)
data_dictionary["mode"] = stats.mode(data)

print(data_dictionary)

{'mean': 6.72, 'median': 7, 'mode': 7}


In [14]:
# To find which statistic do you have to arrange the data in an ascending order?
median


NameError: name 'median' is not defined

In [15]:
#How do you find the median when there are even number of data points?
(n+1)/2

NameError: name 'n' is not defined

In [16]:
#What is the range for the data set
points = [-4,  17,  25,  19,  6,  11,  7]
np.percentile(points, [0,100])

array([-4., 25.])

In [17]:

min_val = min(points)
max_val = max(points)
range_points = max_val - min_val

print("range of the Points data is:", range_points)

range of the Points data is: 29


In [ ]:
# What are outliers in a dataset? 
# Which of the three - Mean, Median, and Mode - is more suseptible to change 
# with presence of outliers in the data?
outliers are the data that have its value extreme from the majority of data
which is suseptible to change MEAN of the data